name: NetBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-12

    strategy:
      fail-fast: false
      matrix:
        version: [8, 9]

    steps:
      - uses: actions/checkout@v2

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: generic/netbsd${{ matrix.version }}
          run: ./test.sh
